### ISSUE TITLE
Create conda package

### ISSUE THREAD

**Issue by MialLewis** [mantidproject/vesuvio#15]
Ultimately, the `vesuvio` code should be able to downloaded and installed as part of a conda package, from the `mantid` channel. To enable this, the following tasks must be completed:

- [x] Create `pip` package #16 
- [x] Wrap `pip` package and extend with necessary conda-only packages (namely `mantid`) #17
- [x] Add scripts to allow for easy interaction from the command line #18
- [ ] Add tests with regards to package building #19
- [x] Publish package on `mantid` conda channel #20
