### ISSUE TITLE
Add unit tests to 85% coverage

### ISSUE THREAD

**Issue by MialLewis** [mantidproject/vesuvio#8]
The `vesuvio` code is currently not covered by unit tests.

Unit tests must be added, satisfying the following tasks:

- [ ] `vesuvio_analysis/core_functions/analysis_functions` #9 
- [ ] `vesuvio_analysis/core_functions/bootstrap` #10 
      `vesuvio_analysis/core_functions/bootstrap_analysis`
- [ ] `vesuvio_analysis/core_functions/fit_in_y_space` #11 
- [ ] `vesuvio_analysis/core_functions/ICHelpers` #12 
      `vesuvio_analysis/core_functions/procedures`
      `vesuvio_analysis/core_functions/run_script`
- [ ] Re-enable coverage requirements #13
